title: "Two Photon Agony"
subtitle: "Endure the Challenges. Emerge a two-photon microscopy legend."
guide: "The Survival Guide"
challenges: "Accept The Challenge"
resources: "Tactical Resources"
troubleshooting: "Troubleshooting"
faq: "FAQ"
email: "kutuzovnp@gmail.com"